resources:
  containers:
  - container: nv-bionic-wasm
    image: nventive/mono-wasm-build:0.7

jobs:
- job: Linux

  container: nv-bionic-wasm

  timeoutInMinutes: 240

  workspace:
    clean: all
      
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  #- bash: |
  #    sudo apt-get update
  #    sudo apt-get install curl libtool automake autoconf g++ cmake gcc-multilib g++-multilib lld lib32ncurses5-dev nuget mono-devel ninja-build mingw-w64 p7zip-full
  - bash: |
      sudo apt-get update
      sudo apt-get install -y python3-pip locales p7zip-full zip

    displayName: Install mono dependencies

  - bash: |
      git clone --recursive https://github.com/jeromelaban/mono -b dev/jela/release-dynamic

    displayName: Clone mono

  - bash: |
      cd mono
      echo "DISABLE_ANDROID=1" > sdks/Make.config
      echo "DISABLE_IOS=1" >> sdks/Make.config
      echo "DISABLE_MAC=1" >> sdks/Make.config
      echo "DISABLE_DESKTOP=1" >> sdks/Make.config
      echo "ENABLE_WASM_DYNAMIC_RUMTIME=1" >> sdks/Make.config
      # echo "ENABLE_WASM_THREADS=1" >> sdks/Make.config
      make -j $(CI_CPU_COUNT) -C sdks/builds provision-wasm

    displayName: Provision Wasm SDK

  - bash: |
      cd mono
      make -j $(CI_CPU_COUNT) -C sdks/builds configure-wasm NINJA=

    displayName: Configure Wasm SDK

  - bash: |
      cd mono
      make -j $(CI_CPU_COUNT) -C sdks/builds build-wasm NINJA=

    displayName: Build Wasm SDK

  - bash: |
      cd mono
      make -j $(CI_CPU_COUNT) -C sdks/builds archive

    displayName: Archive Wasm SDK

  - bash: |
      cd mono
      cp wasm-release-Linux-*.zip $(build.artifactstagingdirectory)
      cp sdks/wasm/*.zip $(build.artifactstagingdirectory)

    displayName: Copy files

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: mono-sdk
      ArtifactType: Container
