jobs:
- job: Mono_Build

  container: unoplatform/mono-wasm-build:1.0

  timeoutInMinutes: 240

  workspace:
    clean: all
      
  pool:
    vmImage: 'ubuntu-latest'
    
  variables:
    CI_CPU_COUNT: 2

  steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y python3-pip locales p7zip-full zip

    displayName: Install mono dependencies

  - bash: |
      git clone --recursive https://github.com/mono/mono 

    displayName: Clone mono

  - bash: |
      set -e
      cd mono
      git reset --hard 9ecb588fc742eb16cf83a6298bf490b06076bcc8
      echo Mono base SHA1: `git rev-parse HEAD`
      git apply $(Build.SourcesDirectory)/build/force-enable-idbfs.patch
      git config --global user.email "ci@platform.uno"
      git config --global user.name "Uno Platform CI"
      git add .
      git commit -m "apply patches"
      echo "ENABLE_WASM=1" > sdks/Make.config
      echo "ENABLE_WASM_THREADS=1" >> sdks/Make.config
      make -j $(CI_CPU_COUNT) -C sdks/builds provision-wasm

    displayName: Provision Wasm SDK

  - bash: |
      cd mono
      make -j $(CI_CPU_COUNT) -C sdks/builds configure-wasm NINJA=

    displayName: Build Wasm SDK

  - bash: |
      cd mono
      make -j $(CI_CPU_COUNT) -C sdks/builds archive-wasm

    displayName: Archive Wasm SDK

  - bash: |
      cd mono
      mkdir -p ./sdks/wasm/sdk/packages
      make -j $(CI_CPU_COUNT) -C sdks/wasm build
      make -j $(CI_CPU_COUNT) -C sdks/wasm package

    displayName: Build Wasm Runtime

  - bash: |
      cd mono
      cp wasm-release-Linux-*.zip $(build.artifactstagingdirectory)
      cp sdks/wasm/*.zip $(build.artifactstagingdirectory)

    displayName: Copy files

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: mono-sdk
      ArtifactType: Container
